FakeCSV/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('generator.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

generator/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("register", views.register, name="register"),
    path("logout", views.logout_view, name="logout"),
    path("create_schema", views.create_schema, name="create_schema"),
    path("update_schema", views.update_schema, name="update_schema"),
    path("delete_schema", views.delete_schema, name="delete_schema"),
    path("create_dataset", views.create_dataset, name="create_dataset"),
]

generator/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import ModelForm

# Create your models here.

class User(AbstractUser):

    def __str__(self):
        return self.username


class Schema(models.Model):
    name = models.CharField(max_length=128)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    modified = models.DateTimeField(auto_now=True)
    DELIMITER_CHOICES = [
        (',', 'Comma (,)'),
        (';', 'Semicolon (;)'),
        (' ', 'Space ( )'),
        ('|', 'Pipe (|)'),
    ]
    delimiter = models.CharField(max_length=2, choices=DELIMITER_CHOICES, default=',', verbose_name='Column separator')
    CHARACTER_CHOICES = [
        ("'", "Single-quote (')"),
        ('"', 'Double-quote (")'),
    ]
    character = models.CharField(max_length=1, choices=CHARACTER_CHOICES, default='"', verbose_name='String character')

    def __str__(self):
        return self.name


class Column(models.Model):
    name = models.CharField(max_length=128, verbose_name='Column name')
    owner = models.ForeignKey(Schema, on_delete=models.CASCADE)
    TYPE_CHOICES = [
        ('name', 'Full name'),
        ('job', 'Job'),
        ('email', 'Email'),
        ('domain_name', 'Domain name'),
        ('phone_number', 'Phone number'),
        ('company', 'Company name'),
        ('paragraph', 'Text'), 
        ('pyint', 'Integer'),
        ('address', 'Address'),
        ('date', 'Date'),
    ]
    type = models.CharField(max_length=12, choices=TYPE_CHOICES)
    start = models.IntegerField(default=0, verbose_name='From')
    end = models.IntegerField(default=0, verbose_name='To')
    order = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.name
    
    
class DataSet(models.Model):
    name = models.CharField(max_length=128)
    owner = models.ForeignKey(Schema, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to='csv')

    def __str__(self):
        return self.name
    
    @property
    def get_file_url(self):
        if self.file and hasattr(self.file, 'url'):
            return self.file.url





        

generator/views.py
import csv
import json
import os
from datetime import datetime

from faker import Faker

from django.contrib.auth import authenticate, login, logout
from django.core.files import File
from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from .models import User, Schema, Column, DataSet


fake = Faker()

# Create your views here.

def login_view(request):
    if request.method == 'POST':
        # Attempt to sign user in
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
        else:
            return render(request, 'generator/login.html', {
                'message': 'Invalid username and/or password.',
                'username': username,
            })
    else:
        return render(request, 'generator/login.html')


def logout_view(request):
    # Logout user
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        new_user = dict(
            username=username, 
            first_name=first_name, 
            last_name=last_name, 
            email=email,
            )
        # Ensure password matches confirmation
        password = request.POST.get('password')
        confirmation = request.POST.get('confirmation')
        if password != confirmation:
            return render(request, 'generator/register.html', {
                'user': new_user,
                'message': 'Passwords must match.',
            })
        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
            user.first_name = first_name
            user.last_name = last_name
            user.save(update_fields=['first_name', 'last_name'])
        except IntegrityError:
                return render(request, 'generator/register.html', {
                'user': new_user,
                'message': 'Username already taken.',
            })
        login(request, user)
        return HttpResponseRedirect(reverse('index'))
    else:
        return render(request, 'generator/register.html')


def index(request):
    # If user is authenticate, show data schemas, else login
    if request.user.is_authenticated:
        queryset = Schema.objects.filter(
                owner=request.user).order_by('modified')
        schemas = list(enumerate(list(queryset), start=1))
        return render(request, 'generator/schemas.html', {
            'schemas': schemas,
        })
    else:
        return render(request, 'generator/login.html')


def create_schema(request):
    # Create new data schema
    if request.method == 'POST':
        # Get schema data from the form
        schema_name = request.POST.get('schema_name')
        schema_delimiter = request.POST.get('schema_delimiter')
        schema_character = request.POST.get('schema_character')
        # Create new schema object
        new_schema = Schema.objects.create(
            name=schema_name,
            delimiter=schema_delimiter,
            character=schema_character,
            owner=request.user,
        )
        # Get columns data from the form
        names = request.POST.getlist('name')
        types = request.POST.getlist('type')
        starts = request.POST.getlist('start')
        ends = request.POST.getlist('end')
        orders = request.POST.getlist('order')
        # Create column objects
        for i in range(len(names)):
            new_column = Column.objects.create(
                name=names[i],
                type=types[i],
                start=starts[i],
                end=ends[i],
                order=orders[i],
                owner=new_schema,
            )
        # Return new schema and datasets representation
        columns = Column.objects.filter(
                owner=new_schema).order_by('order')
        queryset = DataSet.objects.filter(owner=new_schema)
        datasets = list(enumerate(list(queryset), start=1))
        return render(request, 'generator/datasets.html', {
            'schema': new_schema,
            'columns': columns,
            'message': 'New schema successfully created!',
            'datasets': datasets,
        })
        # Return schemas page
        # queryset = Schema.objects.filter(
        #         owner=request.user).order_by('-modified')
        # schemas = list(enumerate(list(queryset), start=1))
        # return render(request, 'generator/schemas.html', {
        #     'schemas': schemas,
        #     'message': 'New schema successfully created!',
        # })
    else:
        columns = [(1, {'start': 0, 'end': 0})]
        return render(request, 'generator/schema.html', {
            'columns': columns
        })


def update_schema(request):
    # Update existing schema
    if request.method == 'GET':
        # Show prepopulated form with schema data
        schema_id = request.GET.get('schema_id')
        schema = Schema.objects.get(pk=schema_id)
        queryset = Column.objects.filter(
                owner=schema_id).order_by('order')
        columns = list(enumerate(list(queryset), start=1))
        return render(request, 'generator/schema.html', {
            'schema': schema,
            'columns': columns,
        })
    else:
        # Get schema data from the form and save changes
        schema_id = request.POST.get('schema_id')
        schema = Schema.objects.get(pk=schema_id)
        schema.name = request.POST.get('schema_name')
        schema.delimiter = request.POST.get('schema_delimiter')
        schema.character = request.POST.get('schema_character')
        schema.save()
        # Get columns data from the form
        names = request.POST.getlist('name')
        types = request.POST.getlist('type')
        starts = request.POST.getlist('start')
        ends = request.POST.getlist('end')
        orders = request.POST.getlist('order')
        # Delete all existing schema columns
        Column.objects.filter(owner=schema_id).delete()
        # Create new schema columns
        for i in range(len(names)):
            new_column = Column.objects.create(
                name=names[i],
                type=types[i],
                start=starts[i],
                end=ends[i],
                order=orders[i],
                owner=schema,
            )
        # Return updated schema and datasets representation
        columns = Column.objects.filter(
                owner=schema_id).order_by('order')
        queryset = DataSet.objects.filter(owner=schema)
        datasets = list(enumerate(list(queryset), start=1))
        return render(request, 'generator/datasets.html', {
            'schema': schema,
            'columns': columns,
            'message': 'Schema successfully updated!',
            'datasets': datasets,
        })
        # Return schemas page
        # queryset = Schema.objects.filter(
        #         owner=request.user).order_by('-modified')
        # schemas = list(enumerate(list(queryset), start=1))
        # return render(request, 'generator/schemas.html', {
        #     'schemas': schemas,
        #     'message': 'Schema successfully updated!',
        # })


def delete_schema(request):
    # Delete existing schema using Delete button
    if request.method == 'POST':
        schema_id = request.POST.get('schema_id')
        schema = Schema.objects.get(pk=schema_id)
        schema.delete()
        return HttpResponseRedirect(reverse('index'))
    else:
        return HttpResponse('Method must be "POST".')


"""Generate fake datasets in csv files using Faker library"""
def get_faker_method(type, *args):
    # Get Faker method to be used to generate fake data
    if getattr(fake, type) and callable(method := getattr(fake, type)):
        if type == 'paragraph':
            return method(fake.pyint(*args))
        else:
            return method(*args)


def create_fake_data(rows_number, columns):
    # Generate fake data records
    rows = []
    for _ in range(rows_number):
        row = {}
        for column in columns:
            if column.type == 'pyint' or column.type == 'paragraph':
                row[column.name] = get_faker_method(
                        column.type, int(column.start), int(column.end))
            else:
                row[column.name] = get_faker_method(column.type)
        rows.append(row)
    return rows


def create_csv_file(file, rows, schema, columns):
    # Create csv file with fake data records
    with open(file, 'w', newline='') as csvfile:
        fieldnames = [column.name for column in columns]
        writer = csv.DictWriter(
                csvfile, 
                fieldnames=fieldnames, 
                delimiter=schema.delimiter, 
                quotechar=schema.character,
                )
        writer.writeheader()
        writer.writerows(rows)


@csrf_exempt
def create_dataset(request):
    if request.method == 'GET':
        # Show existing datasets for chosen schema
        schema_id = request.GET.get('schema_id')
        schema = Schema.objects.get(pk=schema_id)
        columns = Column.objects.filter(owner=schema_id).order_by('order')
        queryset = DataSet.objects.filter(owner=schema_id)
        datasets = list(enumerate(list(queryset), start=1))
        return render(request, 'generator/datasets.html', {
            'schema': schema,
            'columns': columns,
            'datasets': datasets,

generator/templates/generator/datasets.html
{% extends 'generator/layout.html' %}

{% block title %}
Data sets
{% endblock %}

{% block main %}

<!--Action Message, if any-->
{% if message %}
<div id="actMessage" style="display: none">
  {{ message }}
</div>
{% endif %}

<div class="d-flex justify-content-between">
    <div>
        <h2>{{ schema.name }}</h2>
    </div>
    <div>
        <a class="btn btn-primary" href="/update_schema?schema_id={{ schema.id }}" role="button">Edit schema</a>
    </div>
</div>

<!--Data Schema Section-->
<div class="row mb-2">
    <div class="col-1 p-2 fw-bolder">#</div>
    <div class="col-3 p-2 fw-bolder">Column name</div>
    <div class="col-3 p-2 fw-bolder">Column type</div>
    <div class="col-auto"></div>
</div>
{% for column in columns %}
<div class="row">
    <div class="row mb-2">
        <div class="col-1">{{ column.order }}</div>
        <div class="col-3">{{ column.name }}</div>
        <div class="col-3">{{ column.get_type_display }}</div>
        <div class="col-auto"></div>
    </div>
    </div>
{% endfor %}
<!--End of Data Schema Section-->

<div class="d-flex justify-content-between mt-3">
    <div>
        <h2>Data sets</h2>
    </div>
    <div>
        <div class="row">
            <div class="col-auto">
                <label class="form-label" for="id_rows">Rows:</label>
            </div>
            <div class="col-auto">
                <input class="form-control" type="number" min="0" id="id_rows" required>
            </div>
            <div class="col-auto">
                <button class="btn btn-success" type="submit" onclick="createDataSet('{{schema.id}}')">Generate data</button>
            </div>
        </div>
    </div>
</div>
<!--Data Sets Section-->
<div class="row mb-2">
    <div class="col-1 p-2 fw-bolder">#</div>
    <div class="col-3 p-2 fw-bolder">Created</div>
    <div class="col-3 p-2 fw-bolder">Status</div>
    <div class="col-auto p-2 fw-bolder">Actions</div>
</div>
<div id="datasets">
    <div class="row mb-2 d-none" id="dataset1">
        <div class="col-1 dataset-tag" id="number1"></div>
        <div class="col-3 dataset-tag" id="created1"></div>
        <div class="col-3 dataset-tag" id="badge_processing1"><span class="badge bg-secondary">Processing</span></div>
        <div class="col-3 dataset-tag d-none" id="badge_ready1"><span class="badge bg-success">Ready</span></div>
        <div class="col-auto dataset-tag" id="link1"></div>
    </div>
    {% for dataset in datasets %}
    <div class="row mb-2" id="dataset{{dataset.0}}">
        <div class="col-1 dataset-tag" id="number{{dataset.0}}">{{ dataset.0 }}</div>
        <div class="col-3 dataset-tag" id="created{{dataset.0}}">{{ dataset.1.created|date:"Y-m-d H:i:s" }}</div>
        <div class="col-3 dataset-tag" id="badge_ready{{dataset.0}}"><span class="badge bg-success">Ready</span></div>
        <div class="col-auto dataset-tag" id="link{{dataset.0}}"><a href="{{ dataset.1.get_file_url }}">Download</a></div>
    </div>
    {% endfor %}
</div>
<!--End of Data Sets Section-->


{% endblock %}

generator/templates/generator/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="FakeCSV is a generator of csv files with fake data">
    <meta name="author" content="Yuriy Melnykov">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="{% static 'generator/generator.js' %}"></script>
    {% block script %}
    <!--Additional script, if any-->
    {% endblock %}
    <title>
        {% block title %}
        {% endblock %}
    </title>
  </head>

  <body>

    <!--Webpage Header-->
    <header class="container-fluid sticky-top bg-light">
      <div class="container">
        <!--Navigation Bar-->
        <nav class="navbar navbar-expand-lg bg-light">
          <div class="container-fluid">
            <!--Website Logo-->
            <a class="navbar-brand" href="{% url 'index' %}"><span class="h1">FakeCSV</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if user.is_authenticated %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <!--Webpage Links-->
                    {% url 'index' as url %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == url %}active{% endif %}" href="{{ url }}">Schemas</a>
                    </li>
                    {% url 'create_schema' as url %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == url %}active{% endif %}" href="{{ url }}">New schema</a>
                    </li>
                    {% url 'logout' as url %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == url %}active{% endif %}" href="{{ url }}">Logout</a>
                    </li>
                </ul>
                <!--Current User Name-->
                <span class="ms-auto">Hello, <strong>{{ request.user }}</strong></span>
                {% endif %}
            </div>
          </div>
        </nav>
      </div>
    </header>
    <!--End of Webpage Header-->

    <!--Webpage Main Content-->
    <main class="container mt-3">
      {% block main %}
      {% endblock %}
    </main> 
    <!--End of Webpage Main Content-->
  
    <!--Webpage Footer-->
    <footer class="my-3 small text-center text-muted">
      Hand crafted by <a href="mailto:ymelnykov@gmail.com">Yuriy Melnykov</a> 
    </footer>
    <!--End of Webpage Footer-->
  
  </body>
  
</html>

generator/templates/generator/login.html
{% extends "generator/layout.html" %}

{% block title %}
    Login
{% endblock %}

{% block main %}

<!--Action Message, if any-->
{% if message %}
<div id="actMessage" style="display: none">
  {{ message }}
</div>
{% endif %}

<h2>Login</h2>
<!--Login Form-->
<div class="row mb-3">
    <div class="col-sm-2"></div>
    <div class="col-sm-6 small text-muted">Fields marked with "*" are required.</div>
</div>
<form action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <div class="row mb-3">
        <label class="col-sm-2 col-form-label fw-semibold" for="id_username">Username*:</label>
        <div class="col-sm-6">
            <input class="form-control form-control-sm" type="text" name="username" value="{{ username }}" maxlength="150" id="id_username" required>
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-2 col-form-label fw-semibold" for="id_password">Password*:</label>
        <div class="col-sm-6">
            <input class="form-control form-control-sm" type="password" name="password" maxlength="150" id="id_password" required>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-sm-2"></div>
        <div class="col-sm-10">
            <input class="btn btn-primary" type="submit" value="Log in">
        </div>
    </div>
</form>
<!--Register Link-->
<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-10">
        Don't have an account? <a href="{% url 'register' %}">Register here.</a>
    </div>
</div>

{% endblock %}

generator/templates/generator/register.html
{% extends "generator/layout.html" %}

{% block title %}
    Register
{% endblock %}

{% block main %}

<!--Action Message, if any-->
{% if message %}
<div id="actMessage" style="display: none">
  {{ message }}
</div>
{% endif %}

<h2>Register</h2>
<!--Register Form-->
<div class="row mb-3">
    <div class="col-sm-2"></div>
    <div class="col-sm-6 small text-muted">Fields marked with "*" are required.</div>
</div>
<form action="{% url 'register' %}" method="post">
    {% csrf_token %}
    <div class="row">
        <label class="col-sm-2 col-form-label fw-semibold" for="id_username">Username*:</label>
        <div class="col-sm-6">
            <input class="form-control form-control-sm" type="text" name="username" value="{{ user.username }}" maxlength="150" id="id_username" required>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-sm-2"></div>
        <div class="col-sm-10 text-muted" style="font-size: 0.75rem" id="id_username_helptext">
            150 characters or fewer. Letters, digits and @/./+/-/_ only.
        </div>
    </div>
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label fw-semibold" for="id_first_name">First name:</label>
        <div class="col-sm-6">
            <input class="form-control form-control-sm" type="text" name="first_name" value="{{ user.first_name }}" maxlength="150" id="id_first_name">
        </div>
    </div>
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label fw-semibold" for="id_last_name">Last name:</label>
        <div class="col-sm-6">
            <input class="form-control form-control-sm" type="text" name="last_name" value="{{ user.last_name }}" maxlength="150" id="id_last_name">
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-2 col-form-label fw-semibold" for="id_email">Email*:</label>
        <div class="col-sm-6">
            <input class="form-control form-control-sm" type="email" name="email" value="{{ user.email }}" maxlength="254" id="id_email" required>
        </div>
    </div>
    <div class="row">
        <label class="col-sm-2 col-form-label fw-semibold" for="id_password">Password*:</label>
        <div class="col-sm-6">
            <input class="form-control form-control-sm" type="password" name="password" maxlength="150" id="id_password" required>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-sm-2"></div>
        <div class="col-sm-10 text-muted" style="font-size: 0.75rem" id="id_new_password1_helptext">
            <ul>
                <li>Your password can’t be too similar to your other personal information.</li>
                <li>Your password must contain at least 8 characters.</li>
                <li>Your password can’t be a commonly used password.</li>
                <li>Your password can’t be entirely numeric.</li>
            </ul>
        </div>
    </div>
<div class="row mb-3">
        <label class="col-sm-2 col-form-label fw-semibold" for="id_confirmation">Confirm password*:</label>
        <div class="col-sm-6">
            <input class="form-control form-control-sm" type="password" name="confirmation" maxlength="150" id="id_confirmation" required>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-sm-2"></div>
        <div class="col-sm-10">
            <input class="btn btn-primary" type="submit" value="Register">
        </div>
    </div>
</form>
<!--Log in Link-->
<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-10">
        Already have an account? <a href="{% url 'login' %}">Log In here.</a>
    </div>
</div>

{% endblock %}

generator/templates/generator/schema.html
{% extends 'generator/layout.html' %}
{% load static %}

{% block script %}
<script src="{% static 'generator/prePopulateSelects.js' %}"></script>
{% endblock %}

{% block title %}
New schema
{% endblock %}

{% block main %}
<!--Schema form-->
{% if schema %}
<form action="{% url 'update_schema' %}" method="post">
{% else %}
<form action="{% url 'create_schema' %}" method="post">
{% endif %}
    {% csrf_token %}
    <div class="d-flex justify-content-between">
        <div>
            <h2>New schema</h2>
        </div>
        <div>
            <button class="btn btn-success" type="submit">Submit</a>
        </div>
    </div>
    <!--Schema data-->
    <input type="hidden" name="schema_id" value="{{schema.id}}">
    <div class="row">
        <div class="col-6">
            <label class="form-label" for="id_schema_name">Name:</label>
        </div>
        <div class="col-6"></div>
    </div>
    <div class="row mb-2">
        <div class="col-6">
            <input class="form-control" type="text" name="schema_name" maxlength="128" required id="id_schema_name" value="{{ schema.name }}">
        </div>
        <div class="col-6"></div>
    </div>
    <div class="row">
        <div class="col-6">
            <label class="form-label" for="id_schema_delimiter">Column separator:</label>
        </div>
        <div class="col-6"></div>
    </div>
    <div class="row mb-2">
        <div class="col-6">
            <select class="form-select" name="schema_delimiter" id="id_schema_delimiter" data-value="{{ schema.delimiter }}">
                <option value="," selected>Comma (,)</option>
                <option value=";">Semicolon (;)</option>
                <option value=" ">Space ( )</option>
                <option value="|">Pipe (|)</option>
            </select>
        </div>
        <div class="col-6"></div>
    </div>
    <div class="row">
        <div class="col-6">
            <label class="form-label" for="id_schema_character">String character:</label>
        </div>
        <div class="col-6"></div>
    </div>
    <div class="row mb-5">
        <div class="col-6">
            <select class="form-select" name="schema_character" id="id_schema_character" data-value="{{ schema.character }}">
                <option value="&#x27;">Single-quote (&#x27;)</option>
                <option value="&quot;" selected>Double-quote (&quot;)</option>
            </select>
        </div>
        <div class="col-6"></div>
    </div>
    <!--End of Schema data-->
    <!--Columns data-->
    <h2>Schema columns</h2>
    <div id="columns">
        {% for column in columns %}
        <div class="mb-2" id="column{{column.0}}">
            <!--Field labels-->
            <div class="row">
                <div class="col-3">
                    <label class="form-label" for="id_name">Column name:</label>
                </div>
                <div class="col-3">
                    <label class="form-label" for="id_type">Type:</label>
                </div>
                <div class="col-1 invisible range-tag">
                    <label class="form-label" for="id_start">From:</label>
                </div>
                <div class="col-1 invisible range-tag">
                    <label class="form-label" for="id_end">To:</label>
                </div>
                <div class="col-3">
                    <label class="form-label" for="id_order">Order:</label>
                </div>
                <div class="col-1">
                </div>
            </div>
            <!--End of Field labels-->
            <!--Fields-->
            <div class="row">
                <div class="col-3">
                    <input class="form-control me-2 column-tag" type="text" name="name" maxlength="128" required id="id_name" value="{{column.1.name}}">
                </div>
                <div class="col-3">
                    <select class="form-select me-2 column-tag" name="type" onchange="showHideRangeLimits('{{column.0}}')" required id="id_type" data-value="{{column.1.type}}" data-column="{{column.0}}">
                        <option value="" selected>---------</option>
                        <option value="name">Full name</option>
                        <option value="job">Job</option>
                        <option value="email">Email</option>
                        <option value="domain_name">Domain name</option>
                        <option value="phone_number">Phone number</option>
                        <option value="company">Company name</option>
                        <option value="paragraph">Text</option>
                        <option value="pyint">Integer</option>
                        <option value="address">Address</option>
                        <option value="date">Date</option>
                    </select>
                </div>
                <div class="col-1 invisible range-tag">
                    <input class="form-control me-2" type="number" name="start" id="id_start" value="{{column.1.start}}">
                </div>
                <div class="col-1 invisible range-tag">
                    <input class="form-control me-2" type="number" name="end" id="id_end" value="{{column.1.end}}">
                </div>
                <div class="col-3">
                    <input class="form-control me-2 column-tag order-tag" type="number" name="order" min="0" required id="id_order" value="{{column.1.order}}">
                </div>
                <!--End of Fields-->
                <div class="col-1">
                    <button class="btn btn-danger btn-sm" type="button" id="delete" onclick="removeColumn('{{column.0}}')">Delete</button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!--End of Columms data-->
</form>
<button class="btn btn-primary mt-3" onclick="addColumn()" id="add">Add column</button>

{% endblock %}